### ISSUE TITLE
Feature request: horizontal scroll

### ISSUE THREAD

**Issue by ivan-avalos** [openalloc/SwiftTabler#2]

**Comment by reedes** [comment]
I thought about including that directly but decided it wasn't needed.

See the `SidewaysScroller` wrapper in the TabularDemo for example of how to implement.

**Comment by ivan-avalos** [comment]
Doesn't seem like horizontal scroll is working at all. If you attempt to scroll horizontally, it scrolls the containing view, not the table.

**Comment by ivan-avalos** [comment]
Here's a recording: https://user-images.githubusercontent.com/16617314/156291600-e2d642c1-8567-49b6-8cac-3a04f45a3513.mp4

**Comment by ivan-avalos** [comment]
Here's the source code: https://git.sr.ht/~avalos/trackermap-mobile/tree/bb604a0c95fe344a5a5f4392c6bd33bc941b2ce5/item/iosApp/iosApp/Details/Reports/UnitReportsView.swift

You won't be able to use it without a Traccar server and an account, but there you have it for reference and debugging purposes.

**Comment by reedes** [comment]
I just tried TablerDemo with wider values on an iPod touch simulator and it's working as expected, scrolling the table within the SidewaysScroller.

Give that a try to see how it's working.

The lines I changed...

```swift
    private let minWidth: CGFloat = 1000
    private let title = "Tabler Demo"
    
    private var gridItems: [GridItem] = [
        GridItem(.flexible(minimum: 135, maximum: 150), alignment: .leading),
        GridItem(.flexible(minimum: 200, maximum: 400), alignment: .leading),
        GridItem(.flexible(minimum: 190, maximum: 200), alignment: .trailing),
        GridItem(.flexible(minimum: 135, maximum: 150), alignment: .leading),
    ]
```

**Comment by ivan-avalos** [comment]
I can confirm it works with a length of 1000.

**Comment by reedes** [comment]
This project from a project watcher might be relevant: https://github.com/NuPlay/FitScrollView

I haven't had a chance to look at it yet.

**Comment by reedes** [comment]
(Mostly) addressed by new https://github.com/openalloc/SwiftTablerScroller component.

**Comment by reedes** [comment]
Renamed project to https://github.com/openalloc/SwiftSideways
