### ISSUE TITLE
Feature Request : Add an optional footer.

### ISSUE THREAD

**Issue by jjamminjim** [openalloc/SwiftTabler#43]
Would it possible to add an optional footer to the table.

**Comment by reedes** [comment]
It should be feasible to support an optional Footer using the same approach as headers are supported.

However, there's an `init` proliferation problem. The current combination of optional Header, Overlay, and Background require 2^3 (or 8) different inits for each table variation. Yet another optional Footer view will require 2^4 (or 16) inits for each.

Ideally there's a better way to address this problem than manually coding new inits. Code generation (using Sourcery, eg) might be the best option, unless there's a SwiftUI init trick I'm missing.

Pull requests accepted from whoever wishes to tackle this. 😀
